name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: thezurihotels nodejs app
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.SSH_HOST }} # Your server's IP address
          username: ${{ secrets.SSH_USERNAME }} # Your server's username
          key: ${{ secrets.SSH_KEY }} # Your server's SSH private key
          passphrase: ${{ secrets.SSH_PASS }} # Your server's SSH password

          script: |
            cd /home/reactlive/ZuriHotels
            sudo -v
            sudo git pull origin main